import ThreeDModel from "@/ThreeDModel";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Solar System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/solarsystem" />
      </Head>

      <main>
        <ThreeDModel />
      </main>
    </>
  );
}
